name: Build and Deploy on server

on:
  push:
    branches:
      - dev

jobs:
  npm_install:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3
        with:
          node-version: '18' # Replace with your Node.js version, if different

        # Setup key
      - name: Setup key
        run: |
          set -eu
          mkdir -p ~/.ssh
          echo "${{ secrets.SECRET_KEY }}" > ~/.ssh/id_rsa  
          chmod 600 ~/.ssh/id_rsa

      # Build
      - name: Install dependencies
        run: npm ci
      - name: Build
        run: npm run build
        # Deploy
      - name: Deploy
        run: rsync -e "ssh -i ~/.ssh/id_rsa -o StrictHostKeyChecking=no" --archive --compress --delete . ${{secrets.DIGITALOCEAN_USERNAME}}@${{secrets.DIGITALOCEAN_HOST}}:${{secrets.STAGING_PATH}}
        working-directory: ./dist
